<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('pending_messages', function (Blueprint $table) {
            $table->id();

            $table->foreignId('sender_id')
                ->constrained('users')
                ->cascadeOnDelete();

            $table->foreignId('recipient_id')
                ->constrained('users')
                ->cascadeOnDelete();

            /*
             * ID generated by the sender's phone.
             *
             * This allows the same message to be safely retried
             * without creating duplicate server messages.
             */
            $table->uuid('client_message_id');

            $table->text('message');

            /*
             * When the message was originally created.
             */
           

            /*
             * The server must not keep messages forever.
             */
            $table->timestamp('expires_at');

            $table->timestamps();

            /*
             * One sender cannot submit the same client message
             * more than once.
             */
            $table->unique([
                'sender_id',
                'client_message_id',
            ]);

            /*
             * Helps Laravel quickly find messages waiting
             * for a particular recipient.
             */
            $table->index([
                'recipient_id',
                'expires_at',
            ]);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('pending_messages');
    }
};